[project]

site_name = "3dcp.fyi"
repo_url = "https://github.com/dan-auer/3dcp.fyi"
repo_name = "dan-auer/3dcp.fyi"
site_description = "A Database on 3D Concrete Printing"
site_author = "<daniel.auer@tum.de>"
site_url =  "https://3dcp.fyi"

copyright = """
<a href="/impressum">Impressum</a> • <a href="/datenschutz">Datenschutz</a>
"""

nav = [
  { "Home" = "index.md" },
  { "Keyword" = "keyword/index.md"},
  { "Author" = "author/index.md"},
  { "Date" = "date/index.md"},
  ]

extra_css = ["stylesheets/extra.css"]


[project.theme]

# change this to "classic" to use the traditional Material for MkDocs look.
variant = "modern"
custom_dir = "overrides"
logo = "assets/logo.svg"
favicon = "assets/logo.svg"
language = "en"
font = false

features = [
    #"announce.dismiss",
    #"content.action.edit",
    #"content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    "toc.integrate",
]


[[project.theme.palette]]
scheme = "default"
toggle.icon = "ti/sun-off"
toggle.name = "Light Mode"
accent = "blue"
primary = "blue"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "ti/sun"
toggle.name = "Dark Mode"
accent = "orange"
primary = "orange"


[project.theme.icon]
repo = "ti/brand-github"


[project.theme.icon.admonition]
note = "fontawesome/solid/note-sticky"
abstract = "ti/chart-bubble"
info = "ti/blockquote"
tip = "ti/trophy"
success = "ti/users"
question = "ti/user"
warning = "ti/tex"
failure = "ti/file-symlink"
danger = "ti/braces"
bug = "ti/arrow-bar-to-left"
example = "ti/arrow-bar-left"
quote = "ti/sum"

[project.extra]
generator = false

###############################################
[project.extra.tags]

############################


[project.markdown_extensions.abbr]

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.def_list]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"

[project.markdown_extensions.pymdownx.caret]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
options.custom_icons = ["overrides/.icons"]

[project.markdown_extensions.pymdownx.highlight]

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.keys]

[project.markdown_extensions.pymdownx.mark]

[project.markdown_extensions.pymdownx.smartsymbols]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.tilde]